[package]
name = "common-exception"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
common-arrow = { path = "../arrow" }

# GitHub dependencies
# TODO: Use the version from crates.io once
# https://github.com/brendanzab/codespan/pull/331 is released.
codespan-reporting = { git = "https://github.com/brendanzab/codespan", rev = "c84116f5" }

anyhow = { workspace = true }
arrow-schema = "46.0.0"
backtrace = "0.3.69"
bincode = { version = "2.0.0-rc.1", features = ["serde", "std", "alloc"] }
http = "0.2"
opendal = { workspace = true }
parquet = "46.0.0"
paste = "1.0.9"
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
