[package]
name = "common-ast"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = { path = "../../common/exception" }
common-io = { path = "../../common/io" }

# Crates.io dependencies
enum-as-inner = "0.5.1"
ethnum = { workspace = true }
fast-float = "0.2.0"
itertools = "0.10.5"
logos = "0.12.1"
nom = "7.1.1"
nom-rule = "0.3.0"
ordered-float = { workspace = true }
pratt = "0.4.0"
pretty = "0.11.3"
strsim = "0.10"
strum = "0.24"
strum_macros = "0.24"
url = "2.3.1"
serde = { workspace = true }
serde_json = { workspace = true }
num-derive = "0.3.3"
num-traits = "0.2.15"
enumflags2 = { version = "0.7.7", features = ["serde"] }

[dev-dependencies]
common-base = { path = "../../common/base" }
criterion = "0.4"
goldenfile = "1.4"
pretty_assertions = "1.3.0"
regex = "1.8.1"

[[bench]]
name = "bench"
harness = false
