[package]
name = "common-meta-app"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
storage-hdfs = []

[dependencies]
common-exception = { path = "../../common/exception" }
common-io = { path = "../../common/io" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-types = { path = "../types" }

anyerror = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cron = "0.12.0"
enumflags2 = { version = "0.7.7", features = ["serde"] }
hex = "0.4.3"
maplit = "1.0.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = "0.10.5"
sha2 = "0.10.6"
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["num-traits"]

[build-dependencies]
common-building = { path = "../../common/building" }

tonic-build = { workspace = true }
